
SELECT 
    A.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK_SALES C
JOIN BOOK A 
    ON A.BOOK_ID = C.BOOK_ID
JOIN AUTHOR B 
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC