SELECT t.FOOD_TYPE, t.REST_ID, t.REST_NAME, t.FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE, REST_ID, REST_NAME
) AS t
WHERE t.FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    WHERE FOOD_TYPE = t.FOOD_TYPE
)
ORDER BY t.FOOD_TYPE DESC;
