/*
- ANIMAL_OUTS에는 있는데 ANIMAL_IN에는 없는 동물의 
- ID(OUT기준)와 이름(OUT)을 ID 순으로 조회해야함 
- OUT 기준으로 LEFT JOIN
*/
SELECT
    A.ANIMAL_ID,
    A.NAME
FROM ANIMAL_OUTS A
    LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID ASC;
