/*
- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회
- DATETIME 컬럼 case로 정리해서 테이블 구하기 
- 해당 case별로 group by 해서 count 
*/
WITH hours AS (
    SELECT 0 AS MyHour UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL 
    SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL 
    SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL 
    SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL 
    SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL 
    SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL 
    SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL 
    SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
) 
SELECT 
    H.MyHour AS HOUR,
    COUNT(X.ANIMAL_ID) AS COUNT
FROM hours H
LEFT JOIN (
    SELECT
        ANIMAL_ID,
        HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
) X ON H.MyHour = X.HOUR
GROUP BY H.MyHour
ORDER BY H.MyHour;
