/*
- ANIMAL_INS에 있는 DATETIME보다 ANIMAL_OUTS에 있는 DATETIME보다 작은 애들의 
- ID와 이름 
*/

SELECT
    A.ANIMAL_ID,
    A.NAME
FROM ANIMAL_INS A
    JOIN ANIMAL_OUTS B
WHERE A.DATETIME > B.DATETIME AND A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.DATETIME;