#처음에 '해당기간동안'이라는 조건을 파악 못했음. 무언가 안풀릴 때는 조건을 코드에 잘 반영했는지 확인하자
#WITH절 공부 필요

WITH CAR_TOTAL_COUNT AS (
    SELECT 
        CAR_ID,
        COUNT(CAR_ID) AS TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
  AND CAR_ID IN (SELECT CAR_ID FROM CAR_TOTAL_COUNT)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
