-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE  
    EXTRACT(YEAR FROM s.SALES_DATE) = 2022 
    AND 
    EXTRACT(MONTH FROM s.SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;