-- 코드를 입력하세요
SELECT f.CATEGORY, f.PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
WHERE CATEGORY IN('과자','국','김치','식용유') AND
    f.PRICE = (SELECT MAX(price) 
               FROM FOOD_PRODUCT
             WHERE CATEGORY = f.CATEGORY)
GROUP BY CATEGORY
ORDER BY MAX(PRICE) DESC;