/*
- AUTHOR_ID 기준으로 (INNER JOIN) 한 뒤
- WHERE CATEGORY = '경제'로 필터링 
- 결과는 출판일(PUBLISHED_DATE) 기준으로 오름차순
*/

SELECT 
    A.BOOK_ID,
    B.AUTHOR_NAME,
    DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE ASC;